server:
  port: 8888
spring:
  rabbitmq:
    host: 150.158.80.188
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BJPotter/config-repo
          proxy:
            http:
              host: 127.0.0.1
              port: 10809
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
